### ISSUE TITLE
Error while trying to use the action

### ISSUE THREAD

**Issue by hiteshsondhi88** [teriiehina/fastlane-plugin-upload_folder_to_s3#3]
Hey,

Thanks for the wonderful plugin. While trying your plugin I am getting following error -

/Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-plugin-upload_folder_to_s3-0.1.0/lib/fastlane/plugin/upload_folder_to_s3/actions/upload_folder_to_s3_action.rb:72:in `valid_s3': [!] uninitialized constant Fastlane::Actions::UploadFolderToS3Action::AWS (NameError)
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-plugin-upload_folder_to_s3-0.1.0/lib/fastlane/plugin/upload_folder_to_s3/actions/upload_folder_to_s3_action.rb:82:in`valid_bucket'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-plugin-upload_folder_to_s3-0.1.0/lib/fastlane/plugin/upload_folder_to_s3/actions/upload_folder_to_s3_action.rb:21:in `run'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:197:in`block (2 levels) in execute_action'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:182:in`block in execute_action'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:181:in `chdir'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:181:in`execute_action'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:107:in `trigger_action_by_name'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/fast_file.rb:140:in`method_missing'
    from Fastfile:117:in `block (2 levels) in parsing_binding'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/lane.rb:33:in`call'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/lane.rb:33:in `call'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:50:in`block in execute'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:46:in `chdir'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:46:in`execute'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/command_line_handler.rb:30:in`handle'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in`call'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in`run'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in`run!'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:244:in`run'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:20:in `start'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/cli_tools_distributor.rb:47:in`take_off'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/bin/fastlane:5:in `<top (required)>'
    from /Users/ct/.rbenv/versions/2.2.4/bin/fastlane:22:in`load'
    from /Users/ct/.rbenv/versions/2.2.4/bin/fastlane:22:in `<main>'

Can you please help me with resolving the above issue.

Thanks.

**Comment by teriiehina** [comment]
Hi @hiteshsondhi88,

# Short answer

It was a missing dependency. Sorry for that. I released a `0.2.0` version that should correct the error. Could you please use this version and tell me if that fixes the problem ?

# Long answer

This is happening because on my computer, I had the `aws-sdk` gem installed (using a simple `gem install aws-sdk`) but I didn't put that gem in the dependencies of the `fastlane-plugin-upload_folder_to_s3` gem.

Thus on my computer, everything is working as expected but when the `fastlane-plugin-upload_folder_to_s3` gem is installed on a computer that didn't have the `aws-sdk` gem installed, the error you got is occurring.

**Comment by hiteshsondhi88** [comment]
Thanks for the quick turnaround @teriiehina 

I've tried the latest plugin but still facing the same issue.

Here is the stacktrace -

All plugins are up to date
/Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-plugin-upload_folder_to_s3-0.2.0/lib/fastlane/plugin/upload_folder_to_s3/actions/upload_folder_to_s3_action.rb:72:in `valid_s3': [!] uninitialized constant Fastlane::Actions::UploadFolderToS3Action::AWS (NameError)
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-plugin-upload_folder_to_s3-0.2.0/lib/fastlane/plugin/upload_folder_to_s3/actions/upload_folder_to_s3_action.rb:82:in`valid_bucket'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-plugin-upload_folder_to_s3-0.2.0/lib/fastlane/plugin/upload_folder_to_s3/actions/upload_folder_to_s3_action.rb:21:in `run'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:197:in`block (2 levels) in execute_action'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:182:in`block in execute_action'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:181:in `chdir'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:181:in`execute_action'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:107:in `trigger_action_by_name'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/fast_file.rb:140:in`method_missing'
    from Fastfile:117:in `block (2 levels) in parsing_binding'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/lane.rb:33:in`call'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/lane.rb:33:in `call'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:50:in`block in execute'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:46:in `chdir'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:46:in`execute'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/command_line_handler.rb:30:in`handle'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in`call'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in`run'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in`run!'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:244:in`run'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:20:in `start'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/cli_tools_distributor.rb:47:in`take_off'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/bin/fastlane:5:in `<top (required)>'
    from /Users/ct/.rbenv/versions/2.2.4/bin/fastlane:22:in`load'
    from /Users/ct/.rbenv/versions/2.2.4/bin/fastlane:22:in `<main>'

It looks like that you might be using version 1 of aws-sdk. Check this SO post here - http://stackoverflow.com/a/28355512/938012

**Comment by teriiehina** [comment]
Hi @hiteshsondhi88,

sorry about that. Same kind of fix but with the right `gem`, version bumped to `0.3.0`.
Hope I got it right this time.

Thank you for your help.

**Comment by hiteshsondhi88** [comment]
Hi @teriiehina thanks for new version

I've tried it but still got error, good thing is this time error is different.

/Users/ct/.rbenv/versions/2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate aws-sdk-v1-1.66.0, because json-2.0.1 conflicts with json (~> 1.4) (Gem::ConflictError)
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1408:in`activate'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1442:in `block in activate_dependencies'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1428:in`each'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1428:in `activate_dependencies'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1410:in`activate'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/site_ruby/2.2.0/rubygems.rb:220:in `rescue in try_activate'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/site_ruby/2.2.0/rubygems.rb:213:in`try_activate'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in`require'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/plugins/plugin_manager.rb:276:in `block in load_plugins'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/plugins/plugin_manager.rb:268:in`each'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/plugins/plugin_manager.rb:268:in `load_plugins'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:17:in`start'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
    from /Users/ct/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.97.2/bin/fastlane:5:in`<top (required)>'
    from /Users/ct/.rbenv/versions/2.2.4/bin/fastlane:22:in `load'
    from /Users/ct/.rbenv/versions/2.2.4/bin/fastlane:22:in`<main>'

**Comment by teriiehina** [comment]
😆 

OK, I'll install it cleanly later today to have the same setup as you and fix it cleanly. Should be done it 24hours at most.

**Comment by hiteshsondhi88** [comment]
Hi @teriiehina I have fixed above issue and created a PR 

https://github.com/teriiehina/fastlane-plugin-upload_folder_to_s3/pull/4/commits

**Comment by teriiehina** [comment]
Thank you 👍
